//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int IDRequest { get; set; }
        public Nullable<int> PlayerSet1ID { get; set; }
        public Nullable<int> PlayerSet2ID { get; set; }
        public Nullable<int> StatusRequest { get; set; }
    
        public virtual PlayerSet PlayerSet { get; set; }
        public virtual PlayerSet PlayerSet1 { get; set; }
    }
}
