//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendship
    {
        public int id { get; set; }
        public Nullable<int> player1_id { get; set; }
        public Nullable<int> player2_id { get; set; }
    
        public virtual PlayerSet PlayerSet { get; set; }
        public virtual PlayerSet PlayerSet1 { get; set; }
    }
}
