//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TuristaMundialEntitiesDB : DbContext
    {
        public TuristaMundialEntitiesDB()
            : base("name=TuristaMundialEntitiesDB")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlayerSet> PlayerSet { get; set; }
        public virtual DbSet<friendship> friendship { get; set; }
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
    }
}
